version: 0.2

phases:
  build:
    commands:
      - "echo == Build phase =="
      - "echo Bucket: ${TARGET_BUCKET}"
      - "pwd"
      - "ls -la"
      - "aws s3 sync . s3://${TARGET_BUCKET} --delete"
