version: 0.2

phases:
  build:
    commands:
      - "echo == Build phase =="
      - "echo Bucket: ${TARGET_BUCKET}"
      - "pwd"
      - "ls -la"
      - >
        aws s3 sync . s3://${TARGET_BUCKET} --delete
        --exclude '.git/*'
        --exclude '.gitignore'
        --exclude 'buildspec.yml'
        --exclude 'README.md'
        --exclude 'generate-og-image.html'
        --exclude 'resume.html'
        --exclude 'infra/*'

  post_build:
    commands:
      - "echo == CloudFront invalidation =="
      - >
        aws cloudfront create-invalidation
        --distribution-id ${CLOUDFRONT_DIST_ID}
        --paths "/*"
